## Each new term in the Fibonacci sequence is generated by adding the previous
## two terms. By starting with 1 and 2, the first 10 terms will be:
##
## 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
##
## By considering the terms in the Fibonacci sequence whose values do not exceed
## four million, find the sum of the even-valued terms.


## Helper function to generate fibonacci number upto 'max'
FibonacciIterateUntil <- function(max, list=c(1, 2)) {
  # Get the last and the second last element
  a <- list[length(list)]
  b <- list[length(list) - 1]

  nextNumber <- a + b

  # If the next element is bigger than our maximum, then we stop generating
  # anymore fibonacci numbers
  if (nextNumber >= max) return(list)

  # Else we continue generating fibonacci number, appeding our next number into
  # the list
  return(FibonacciIterateUntil(max, c(list, nextNumber)))
}

# Generate upto 4 million fibonacchi numbers
list <- FibonacciIterateUntil(4 * 10 ** 6)

# Sum up all the even numbers
sum = 0
for (number in list)
  if(number %% 2 == 0)
    sum <- sum + number

print(sum)